CREATE TABLE `BLOG_ARTICLE` (
    `ID`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键' ,
    `TITLE`  varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '标题' ,
    `CATEGORY`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '分类' ,
    `CONTEXT`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '内容' ,
    `READ_NUM`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '阅读数量' ,
    `POINT_NUM`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '点赞数量' ,
    `OPENED`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '是否公开' ,
    `TOP`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '是否置顶' ,
    `ARTICLE_CAT`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '文章类型' ,
    `TS`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '时间戳' ,
    `CREAT_ID`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '时间戳' ,
    `CREAT_TIME`  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '时间戳' ,
    PRIMARY KEY (`ID`)
) comment '博客文章'
    ENGINE=InnoDB
    DEFAULT CHARACTER SET=utf8 COLLATE=utf8_bin
    ROW_FORMAT=DYNAMIC
;
